### ISSUE TITLE
Huffman Coding

### ISSUE THREAD

**Issue by salonishah01** [AshwinKushwah/Data_Structure_and_Algorithms#39]
Pitch : Huffman Coding is a technique of compressing data to reduce its size without losing any of the details. It was first developed by David Huffman.

Huffman Coding is generally useful to compress the data in which there are frequently occurring characters.

I would like to contribute the code for huffman coding.

**Comment by AshwinKushwah** [comment]
Follow the steps mentioned in the Readme file. Contributions are always welcomed.
